
==================================================================
# PredIt: Natural Language Processing & Predictive Text
##Bennet Voorhees | bennet.voorhees@gmail.com

##Description  
This project was the capstone project for the [Data Science Specialization Certificate](https://www.coursera.org/specializations/jhudatascience?utm_medium=courseDescripTop) offered via Coursera and the Johns Hopkins University. 

The aim of the project was to build a text prediction app (inspired by the SwiftKeyTM application for iOS and Android). I developed the app in Shiny/R using a coprora of text from Twitter, news articles, and blogs. A naive bayes classifier algorithm is used to make predictions of the next word based on the previous n words. 

This repo showcases all of the slides, data, and files for my Coursera final project.

I passed this project, as well as all other courses in the Data Science specialization, with distinction (grade of 90% or better).

##Link to application
The application (developed in Shiny) can be found [here](http://bit.ly/1QN3v5x). Please allow the application a few moments to initialize. 


##This directory  includes the following:

- `README.txt` - what you are reading at this very moment in time. 

- `.R files` - files used to clean text corpora and develop prediction algorithm

- slide deck: contains all of slides I used to make a pitch for the application for the course.  

- app folder: contains the server.R and ui.R files to make the application in Shiny
